version: "3.7"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - server_cache:/data/nginx/cache:rw

  server:
    build:
      context: ./
    volumes:
      - /app/node_modules
      - ./src/:/app/src/

volumes:
  server_cache:
    driver: local
